logging:
  config: classpath:logback/logback-spring.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

jwt:
  access-header: access-token
  refresh-header: refresh-token
  secret: UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290UGFya1N1bmdId2FuLXRpbC1kaWFyeS1zcHJpbmdib290Cg==
  access-token-validity-in-seconds: 600
  refresh-token-validity-in-seconds: 86400

open-ai:
  url: https://api.openai.com/v1/chat/completions
  api-key: ${OPEN_AI_API_KEY}

spring:
  profiles:
    default: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: goldroad
    password: root
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:~/goldroad
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true